/**
 * The deterministic pipeline supervisor (local-only). A plain async state machine
 * sequences the stages; an LLM never decides control flow. Models are called only
 * at role-points (implement, review, classify). Every event is journaled to the
 * decision log before its side effect.
 *
 * The plan is human-authored (loaded, not generated by a model); escalation halts
 * the run and notifies the operator (there is no automated arbiter).
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AssistantMessage } from "@earendil-works/pi-ai";
import type { PipelineConfig } from "./config.ts";
import { DecisionLog, renderSummary } from "./decision-log.ts";
import { notifyEscalation } from "./escalate.ts";
import { redCheck, runGateA, runSmoke } from "./gate-a.ts";
import { gateBRoundDecision, runGateB } from "./gate-b.ts";
import { runImplementer } from "./implementer.ts";
import { buildRoleModels, healthCheck, resolveServerContextWindows } from "./models.ts";
import { loadPlan } from "./plan-loader.ts";
import { classifyFindings, writeAccepted, writeDeferred } from "./revise.ts";
import { makeSafetyGate } from "./safety-gate.ts";
import type { DecisionEvent, Finding, Phase, Plan } from "./schemas.ts";
import { describeImplementerTurn } from "./turn.ts";
import type { PipelineHooks, PipelineTurn, RunResult } from "./types.ts";
import {
	createWorktree,
	getDiff,
	pruneStaleWorktrees,
	removeWorktree,
	type Worktree,
	writePlanTests,
} from "./worktree.ts";

function generateRunId(slug: string): string {
	return `${slug}-${Date.now().toString(36)}`;
}

function buildImplementPrompt(plan: Plan): string {
	const testList = plan.tests.map((t) => `- ${t.path}`).join("\n");
	const runLine = plan.commands.test
		? `Run the tests with EXACTLY this command (do NOT run the whole test suite, e.g. a bare \`npm test\`): ${plan.commands.test}`
		: "Implement the change so these tests pass.";
	return ["# Spec", plan.spec, "", "# Failing tests to make pass (do not edit them)", testList, "", runLine].join(
		"\n",
	);
}

function buildRepairPrompt(plan: Plan, failureSummary: string): string {
	return [
		"The checks are still failing. Fix the implementation so they pass. Do not edit the tests.",
		"",
		"# Failures",
		failureSummary,
		"",
		`# Spec (reference)`,
		plan.spec,
	].join("\n");
}

function buildFindingsRepairPrompt(plan: Plan, findings: Finding[]): string {
	const list = findings
		.map(
			(f) =>
				`- [${f.severity ?? "?"}] (${f.rubricRef})${f.file ? ` ${f.file}${f.line ? `:${f.line}` : ""}` : ""}: ${f.issue}`,
		)
		.join("\n");
	return [
		"Address these reviewer findings without breaking the passing tests:",
		"",
		list,
		"",
		"# Spec (reference)",
		plan.spec,
	].join("\n");
}

export async function runPipeline(
	planDir: string,
	config: PipelineConfig,
	hooks: PipelineHooks = {},
): Promise<RunResult> {
	const plan = await loadPlan(planDir);
	const runId = generateRunId(plan.slug);
	const runDir = join(config.runsDir, runId);
	await mkdir(runDir, { recursive: true });
	const log = await DecisionLog.open(join(runDir, "decision-log.jsonl"));
	const events: DecisionEvent[] = [];
	// "plan" is the setup stage (load / health check / worktree) before the first
	// phase_enter; tracked so an uncaught error is attributed to the right phase.
	let currentPhase: Phase = "plan";

	const emit = async (event: DecisionEvent): Promise<void> => {
		events.push(event);
		await log.append(event);
		hooks.onEvent?.(event);
	};

	const enterPhase = async (phase: Phase, attempt: number): Promise<void> => {
		currentPhase = phase;
		await emit({ type: "phase_enter", phase, attempt });
	};

	const usageSink = (role: string, modelId: string) => (message: AssistantMessage) => {
		void emit({
			type: "usage",
			role,
			model: modelId,
			tokens: message.usage.totalTokens,
			costUsd: message.usage.cost.total,
		});
	};

	// Surface a completed role-turn for live presentation (TUI / CLI). Additive to
	// the decision log; never journaled.
	const turn = (t: PipelineTurn): void => {
		hooks.onTurn?.(t);
	};

	const escalateAndHalt = async (reason: string, openFindings: Finding[]): Promise<RunResult> => {
		await enterPhase("escalate", 1);
		await notifyEscalation(
			{ reason, planSlug: plan.slug, summary: `${reason}. Plan: ${plan.slug} — ${plan.goal}`, openFindings },
			hooks,
		);
		await emit({ type: "escalate", reason });
		turn({ role: "escalate", reason });
		return { status: "failed", runId, planSlug: plan.slug, runDir, smokePassed: false, reason };
	};

	await writeFile(join(runDir, "spec.md"), plan.spec, "utf-8");
	await writeFile(join(runDir, "rubric.md"), plan.rubric.map((c) => `- ${c}`).join("\n"), "utf-8");

	let worktree: Worktree | undefined;

	try {
		await emit({ type: "run_start", runId, planSlug: plan.slug });
		// Match each model's contextWindow to its live server n_ctx before use.
		const models = buildRoleModels(await resolveServerContextWindows(config, hooks.signal));
		// Per-call-site implementer hook: usage accounting + a rendered turn. phase
		// and attempt are captured here since onMessage only sees the message.
		const implementerTurns =
			(phase: Phase, attempt: number) =>
			(message: AssistantMessage): void => {
				usageSink("implementer", models.qwen.id)(message);
				turn({ role: "implementer", phase, attempt, ...describeImplementerTurn(message) });
			};
		await healthCheck(
			[
				{ label: "qwen (implementer)", model: models.qwen, apiKey: config.qwen.apiKey },
				{ label: "gemma (reviewer)", model: models.gemma, apiKey: config.gemma.apiKey },
			],
			hooks.signal,
		);

		await pruneStaleWorktrees(config.repoRoot, hooks.signal);
		worktree = await createWorktree(config.repoRoot, config.worktreesDir, runId, config.baseRef, hooks.signal);
		const safetyGate = makeSafetyGate(worktree.path, Math.floor(config.implementerBashTimeoutMs / 1000));

		// Stage 0 (Phase 1): plan is human-authored. Write tests and prove they fail red.
		await enterPhase("red_check", 1);
		await writePlanTests(worktree.path, plan.tests);
		const red = await redCheck(plan, worktree.path, config.commandTimeoutMs, hooks.signal);
		await emit({ type: "red_check", passed: red.passed, exitCode: red.exitCode });
		turn({ role: "red_check", passed: red.passed });
		if (!red.passed) {
			return await escalateAndHalt("red-check failed: tests pass against the base tree (vacuous plan)", []);
		}

		// Gate A: implement -> test/lint/type, loop to green or cap.
		let gateASummary = "";
		let gateAPassed = false;
		for (let attempt = 1; attempt <= config.caps.gateA; attempt++) {
			await enterPhase("implement", attempt);
			const prompt = attempt === 1 ? buildImplementPrompt(plan) : buildRepairPrompt(plan, gateASummary);
			const impl = await runImplementer(models.qwen, worktree.path, prompt, {
				apiKey: config.qwen.apiKey,
				maxTurns: config.implementerMaxTurns,
				beforeToolCall: safetyGate,
				onMessage: implementerTurns("implement", attempt),
				signal: hooks.signal,
				compaction: config.compaction,
			});
			await emit({ type: "implement", attempt, stopReason: impl.stopReason });

			await enterPhase("gate_a", attempt);
			const gateA = await runGateA(plan, worktree.path, config.commandTimeoutMs, hooks.signal);
			gateASummary = gateA.summary;
			await emit({ type: "gate_a", attempt, passed: gateA.passed, summary: gateA.summary });
			turn({ role: "gate_a", attempt, passed: gateA.passed, summary: gateA.summary });
			if (gateA.passed) {
				gateAPassed = true;
				break;
			}
		}
		if (!gateAPassed) {
			return await escalateAndHalt("gate A cap exceeded", []);
		}

		// Gate B: review -> revise, loop to approve or cap.
		let approved = false;
		for (let attempt = 1; attempt <= config.caps.gateB; attempt++) {
			await enterPhase("gate_b", attempt);
			const diff = await getDiff(worktree.path, hooks.signal);
			const review = await runGateB(models.gemma, plan, diff, {
				apiKey: config.gemma.apiKey,
				signal: hooks.signal,
				onMessage: usageSink("reviewer", models.gemma.id),
			});
			await emit({ type: "gate_b", attempt, verdict: review.verdict, findingCount: review.findings.length });
			turn({ role: "gate_b", attempt, verdict: review.verdict, findings: review.findings });
			// Severity-based gate (fail-closed on severity; see gateBRoundDecision):
			// accept on approve or no blocking finding; escalate when a blocking finding
			// remains on the last allowed round (a further revise could never be reviewed);
			// otherwise revise. Accepted minor findings are recorded, not blocking —
			// otherwise the deliberately-skeptical reviewer never converges.
			const decision = gateBRoundDecision(review.verdict, review.findings, attempt, config.caps.gateB);
			if (decision === "accept") {
				await writeAccepted(runDir, review.findings);
				approved = true;
				break;
			}
			if (decision === "escalate_cap") {
				return await escalateAndHalt("gate B cap exceeded: review still requests changes", review.findings);
			}

			await enterPhase("revise", attempt);
			const classification = await classifyFindings(
				models.qwen,
				review.findings,
				config.qwen.apiKey,
				hooks.signal,
				usageSink("implementer", models.qwen.id),
			);
			await writeDeferred(runDir, classification.deferred);
			await emit({
				type: "revise",
				fixed: classification.toFix.length,
				defended: classification.defended,
				deferred: classification.deferred.length,
			});
			turn({
				role: "revise",
				attempt,
				fixed: classification.toFix.length,
				defended: classification.defended,
				deferred: classification.deferred.length,
			});

			const toAddress = [...classification.toFix, ...classification.stillOpen];
			if (toAddress.length === 0) {
				// Nothing actionable this round (every finding defended or deferred); re-review
				// the unchanged diff next round. Bounded by the cap check above, which
				// escalates once the review rounds are exhausted.
				continue;
			}

			const impl = await runImplementer(models.qwen, worktree.path, buildFindingsRepairPrompt(plan, toAddress), {
				apiKey: config.qwen.apiKey,
				maxTurns: config.implementerMaxTurns,
				beforeToolCall: safetyGate,
				onMessage: implementerTurns("revise", attempt),
				signal: hooks.signal,
				compaction: config.compaction,
			});
			await emit({ type: "implement", attempt, stopReason: impl.stopReason });

			// Regression: the fix must leave Gate A green. A local model often
			// introduces a transient break while addressing findings, so allow it
			// the same bounded repair loop the initial Gate A gets (re-prompt with
			// the failure summary) before escalating — escalation is the fallback,
			// not the first response.
			await enterPhase("gate_a", attempt);
			let regression = await runGateA(plan, worktree.path, config.commandTimeoutMs, hooks.signal);
			await emit({ type: "gate_a", attempt, passed: regression.passed, summary: regression.summary });
			turn({ role: "gate_a", attempt, passed: regression.passed, summary: regression.summary });
			for (let repair = 1; !regression.passed && repair <= config.caps.gateA; repair++) {
				await enterPhase("implement", attempt);
				const fix = await runImplementer(models.qwen, worktree.path, buildRepairPrompt(plan, regression.summary), {
					apiKey: config.qwen.apiKey,
					maxTurns: config.implementerMaxTurns,
					beforeToolCall: safetyGate,
					onMessage: implementerTurns("implement", attempt),
					signal: hooks.signal,
					compaction: config.compaction,
				});
				await emit({ type: "implement", attempt, stopReason: fix.stopReason });
				await enterPhase("gate_a", attempt);
				regression = await runGateA(plan, worktree.path, config.commandTimeoutMs, hooks.signal);
				await emit({ type: "gate_a", attempt, passed: regression.passed, summary: regression.summary });
				turn({ role: "gate_a", attempt, passed: regression.passed, summary: regression.summary });
			}
			if (!regression.passed) {
				return await escalateAndHalt("revise broke Gate A and could not recover", toAddress);
			}
			// The next loop iteration re-reviews the revised diff; the cap check at the top
			// of the loop bounds the total number of review rounds.
		}
		// Reachable only when caps.gateB is 0 (the loop never runs); a normal run either
		// approves (break) or escalates from inside the loop.
		if (!approved) {
			return await escalateAndHalt("review not approved", []);
		}

		// Definition of Done: live-smoke through the real surface.
		const smoke = await runSmoke(plan, worktree.path, config.commandTimeoutMs, hooks.signal);
		await emit({ type: "done", smokePassed: smoke.passed });
		turn({ role: "done", passed: smoke.passed });
		if (!smoke.passed) {
			return {
				status: "failed",
				runId,
				planSlug: plan.slug,
				runDir,
				smokePassed: false,
				reason: "live-smoke failed",
			};
		}
		return { status: "done", runId, planSlug: plan.slug, runDir, smokePassed: true };
	} catch (error) {
		const aborted = hooks.signal?.aborted === true;
		const message = error instanceof Error ? error.message : String(error);
		await emit({ type: "error", phase: currentPhase, message });
		return {
			status: aborted ? "aborted" : "failed",
			runId,
			planSlug: plan.slug,
			runDir,
			smokePassed: false,
			reason: message,
		};
	} finally {
		await writeFile(join(runDir, "summary.md"), renderSummary(plan.slug, events), "utf-8");
		if (worktree) {
			try {
				await removeWorktree(config.repoRoot, worktree, hooks.signal);
			} catch {
				// Best-effort cleanup; a stale worktree is pruned on the next run.
			}
		}
	}
}
